export type BookingFinalizationCopy = {
  subject: string;
  heading: string;
  intro: string;
  instructions: string;
  confirmCta: string;
  questionCta: string;
  retainNote: string;
  manageIntro: string;
  modifyCta: string;
  cancelCta: string;
  closing: string;
  sections: {
    fees: string;
    booking: string;
    billing: string;
    delivery: string;
  };
  labels: {
    bookingCode: string;
    car: string;
    period: string;
    rentalFee: string;
    insurance: string;
    deposit: string;
    deliveryFee: string;
    extrasFee: string;
    extrasList: string;
    adults: string;
    children: string;
    contactName: string;
    contactEmail: string;
    contactPhone: string;
    invoiceName: string;
    invoiceEmail: string;
    invoicePhone: string;
    invoiceAddress: string;
    deliveryLocation: string;
    deliveryType: string;
    deliveryAddress: string;
    arrivalFlight: string;
    departureFlight: string;
    totalLabel: string;
  };
  signatureRole: string;
  signatureLocation: string;
  signatureWebsite: string;
  signatureSlogans: string[];
};

const BASE_EN: BookingFinalizationCopy = {
  subject: 'Booking finalization',
  heading: 'Booking finalization',
  intro: 'Here is a summary of every fee and detail we currently have for your booking.',
  instructions:
    'Please review the data below and confirm your reservation or let us know if anything needs attention. Free cancellation is available up to 48 hours before the rental start.',
  confirmCta: 'Confirm my booking',
  questionCta: 'I have a question',
  retainNote:
    'Please keep this email in your inbox. If you ever need to update or cancel the reservation, you can do it directly from here.',
  manageIntro: 'Need to make changes later? Use the buttons below any time.',
  modifyCta: 'Modify booking',
  cancelCta: 'Cancel booking',
  closing: 'Best regards',
  sections: {
    fees: 'Fee summary',
    booking: 'Booking data',
    billing: 'Billing details',
    delivery: 'Delivery / Pickup',
  },
  labels: {
    bookingCode: 'Booking ID',
    car: 'Car',
    period: 'Rental period',
    rentalFee: 'Rental fee',
    insurance: 'Insurance',
    deposit: 'Deposit',
    deliveryFee: 'Delivery fee',
    extrasFee: 'Extras fee',
    extrasList: 'Requested extras',
    adults: 'Adults',
    children: 'Children',
    contactName: 'Contact name',
    contactEmail: 'Contact email',
    contactPhone: 'Contact phone',
    invoiceName: 'Billing name',
    invoiceEmail: 'Billing email',
    invoicePhone: 'Billing phone',
    invoiceAddress: 'Billing address',
    deliveryLocation: 'Delivery location',
    deliveryType: 'Delivery type',
    deliveryAddress: 'Delivery address',
    arrivalFlight: 'Arrival flight',
    departureFlight: 'Departure flight',
    totalLabel: 'Total',
  },
  signatureRole: 'Rental operations advisor',
  signatureLocation: 'Fuerteventura & Lanzarote',
  signatureWebsite: 'https://zodiacsrentacar.com/en',
  signatureSlogans: ['Freedom leads.', 'Comfort follows.'],
};

const FINALIZATION_COPY: Record<string, BookingFinalizationCopy> = {
  en: BASE_EN,
  hu: {
    ...BASE_EN,
    subject: 'Foglalás véglegesítése',
    heading: 'Foglalás véglegesítése',
    intro:
      'Az alábbiakban összegyűjtöttük a foglalásodhoz kapcsolódó összes díjat és adatot.',
    instructions:
      'Kérjük, ellenőrizd az információkat, majd erősítsd meg a foglalást vagy jelezd, ha kérdésed van. A foglalást díjmentesen legkésőbb az indulás előtt 48 órával mondhatod le.',
    confirmCta: 'Megerősítem a foglalást',
    questionCta: 'Kérdésem van',
    retainNote:
      'Kérjük, ne töröld ezt az e-mailt. Ha később módosítani vagy törölni szeretnéd a foglalást, innen bármikor megteheted.',
    manageIntro:
      'Változtatnál a foglaláson? Használd az alábbi gombokat a módosításhoz vagy törléshez.',
    modifyCta: 'Foglalás módosítása',
    cancelCta: 'Foglalás törlése',
    closing: 'Üdvözlettel',
    sections: {
      fees: 'Díjak összesítése',
      booking: 'Foglalási adatok',
      billing: 'Számlázási adatok',
      delivery: 'Kiszállítás / Átvétel',
    },
    labels: {
      bookingCode: 'Foglalás azonosító',
      car: 'Autó',
      period: 'Időszak',
      rentalFee: 'Bérleti díj',
      insurance: 'Biztosítás',
      deposit: 'Kaució',
      deliveryFee: 'Kiszállítás díja',
      extrasFee: 'Extrák díja',
      extrasList: 'Kért extrák',
      adults: 'Felnőttek',
      children: 'Gyerekek',
      contactName: 'Kapcsolattartó',
      contactEmail: 'Kapcsolattartó e-mail',
      contactPhone: 'Kapcsolattartó telefon',
      invoiceName: 'Számlázási név',
      invoiceEmail: 'Számlázási e-mail',
      invoicePhone: 'Számlázási telefon',
      invoiceAddress: 'Számlázási cím',
      deliveryLocation: 'Kiszállítás helye',
      deliveryType: 'Kiszállítás típusa',
      deliveryAddress: 'Kiszállítás címe',
      arrivalFlight: 'Érkező járat',
      departureFlight: 'Távozó járat',
      totalLabel: 'Összesen',
    },
    signatureRole: 'Autóbérlési tanácsadó',
    signatureLocation: 'Fuerteventura & Lanzarote',
    signatureWebsite: 'https://zodiacsrentacar.com/hu',
    signatureSlogans: ['A szabadság vezet.', 'A kényelem elkísér.'],
  },
  de: {
    ...BASE_EN,
    subject: 'Buchung abschließen',
    heading: 'Buchung abschließen',
    intro:
      'Hier finden Sie eine Zusammenfassung aller Gebühren und Daten, die wir derzeit zu Ihrer Buchung haben.',
    instructions:
      'Bitte prüfen Sie alle Angaben und bestätigen Sie die Buchung oder teilen Sie uns mit, falls es Fragen gibt. Eine kostenfreie Stornierung ist bis spätestens 48 Stunden vor Mietbeginn möglich.',
    confirmCta: 'Buchung bestätigen',
    questionCta: 'Ich habe eine Frage',
    retainNote:
      'Bitte löschen Sie diese E-Mail nicht. Wenn Sie Ihre Buchung später ändern oder stornieren möchten, können Sie das direkt hier erledigen.',
    manageIntro:
      'Nutzen Sie die Schaltflächen unten, um Ihre Buchung bei Bedarf anzupassen oder zu stornieren.',
    modifyCta: 'Buchung ändern',
    cancelCta: 'Buchung stornieren',
    closing: 'Mit freundlichen Grüßen',
    sections: {
      fees: 'Kostenübersicht',
      booking: 'Buchungsdaten',
      billing: 'Rechnungsdaten',
      delivery: 'Lieferung / Abholung',
    },
    labels: {
      bookingCode: 'Buchungsnummer',
      car: 'Fahrzeug',
      period: 'Mietzeitraum',
      rentalFee: 'Mietpreis',
      insurance: 'Versicherung',
      deposit: 'Kaution',
      deliveryFee: 'Liefergebühr',
      extrasFee: 'Aufpreis für Extras',
      extrasList: 'Gewählte Extras',
      adults: 'Erwachsene',
      children: 'Kinder',
      contactName: 'Kontaktperson',
      contactEmail: 'E-Mail',
      contactPhone: 'Telefon',
      invoiceName: 'Rechnungsname',
      invoiceEmail: 'Rechnungs-E-Mail',
      invoicePhone: 'Rechnungstelefon',
      invoiceAddress: 'Rechnungsadresse',
      deliveryLocation: 'Lieferort',
      deliveryType: 'Lieferart',
      deliveryAddress: 'Lieferadresse',
      arrivalFlight: 'Ankunftsflug',
      departureFlight: 'Abflugsnummer',
      totalLabel: 'Gesamt',
    },
    signatureRole: 'Berater für Mietwagenbetrieb',
    signatureLocation: 'Fuerteventura & Lanzarote',
    signatureWebsite: 'https://zodiacsrentacar.com/de',
    signatureSlogans: ['Freiheit führt.', 'Komfort begleitet.'],
  },
  ro: {
    ...BASE_EN,
    subject: 'Finalizarea rezervării',
    heading: 'Finalizarea rezervării',
    intro:
      'Mai jos găsești toate taxele și detaliile cunoscute în acest moment pentru rezervarea ta.',
    instructions:
      'Te rugăm să verifici datele și să confirmi rezervarea sau să ne anunți dacă ai întrebări. Anularea este gratuită până la cel târziu 48 de ore înainte de începutul închirierii.',
    confirmCta: 'Confirmă rezervarea',
    questionCta: 'Am o întrebare',
    retainNote:
      'Te rugăm să păstrezi acest e-mail. Dacă vei dori mai târziu să modifici sau să anulezi rezervarea, o poți face direct de aici.',
    manageIntro:
      'Folosește butoanele de mai jos pentru a modifica sau anula oricând ai nevoie.',
    modifyCta: 'Modifică rezervarea',
    cancelCta: 'Anulează rezervarea',
    closing: 'Cu stimă',
    sections: {
      fees: 'Sumar taxe',
      booking: 'Date rezervare',
      billing: 'Detalii facturare',
      delivery: 'Livrare / Preluare',
    },
    labels: {
      bookingCode: 'ID rezervare',
      car: 'Mașină',
      period: 'Perioadă închiriere',
      rentalFee: 'Taxă de închiriere',
      insurance: 'Asigurare',
      deposit: 'Depozit',
      deliveryFee: 'Taxă de livrare',
      extrasFee: 'Taxă extraopțiuni',
      extrasList: 'Extraopțiuni solicitate',
      adults: 'Adulți',
      children: 'Copii',
      contactName: 'Persoană de contact',
      contactEmail: 'Email contact',
      contactPhone: 'Telefon contact',
      invoiceName: 'Nume facturare',
      invoiceEmail: 'Email facturare',
      invoicePhone: 'Telefon facturare',
      invoiceAddress: 'Adresă facturare',
      deliveryLocation: 'Loc livrare',
      deliveryType: 'Tip livrare',
      deliveryAddress: 'Adresă livrare',
      arrivalFlight: 'Zbor sosire',
      departureFlight: 'Zbor plecare',
      totalLabel: 'Total',
    },
    signatureRole: 'Consilier operațiuni închirieri',
    signatureLocation: 'Fuerteventura & Lanzarote',
    signatureWebsite: 'https://zodiacsrentacar.com/ro',
    signatureSlogans: ['Libertatea te conduce.', 'Confortul te însoțește.'],
  },
  fr: {
    ...BASE_EN,
    subject: 'Finalisation de la réservation',
    heading: 'Finalisation de la réservation',
    intro:
      'Voici un récapitulatif de tous les frais et informations connus à ce jour pour votre réservation.',
    instructions:
      'Veuillez vérifier les données ci-dessous et confirmer votre réservation ou nous faire part de vos questions. L’annulation est gratuite jusqu’à 48 heures avant le début de la location.',
    confirmCta: 'Je confirme ma réservation',
    questionCta: 'J’ai une question',
    retainNote:
      'Merci de conserver cet e-mail. Si vous devez modifier ou annuler la réservation plus tard, vous pouvez le faire directement ici.',
    manageIntro:
      'Utilisez les boutons ci-dessous pour modifier ou annuler votre réservation si nécessaire.',
    modifyCta: 'Modifier la réservation',
    cancelCta: 'Annuler la réservation',
    closing: 'Cordialement',
    sections: {
      fees: 'Résumé des frais',
      booking: 'Données de réservation',
      billing: 'Détails de facturation',
      delivery: 'Livraison / Retrait',
    },
    labels: {
      bookingCode: 'ID de réservation',
      car: 'Véhicule',
      period: 'Période de location',
      rentalFee: 'Frais de location',
      insurance: 'Assurance',
      deposit: 'Caution',
      deliveryFee: 'Frais de livraison',
      extrasFee: 'Frais des options',
      extrasList: 'Options demandées',
      adults: 'Adultes',
      children: 'Enfants',
      contactName: 'Contact',
      contactEmail: 'Email du contact',
      contactPhone: 'Téléphone du contact',
      invoiceName: 'Nom de facturation',
      invoiceEmail: 'Email de facturation',
      invoicePhone: 'Téléphone de facturation',
      invoiceAddress: 'Adresse de facturation',
      deliveryLocation: 'Lieu de livraison',
      deliveryType: 'Type de livraison',
      deliveryAddress: 'Adresse de livraison',
      arrivalFlight: 'Vol d’arrivée',
      departureFlight: 'Vol de départ',
      totalLabel: 'Total',
    },
    signatureRole: 'Conseiller opérations de location',
    signatureLocation: 'Fuerteventura & Lanzarote',
    signatureWebsite: 'https://zodiacsrentacar.com/fr',
    signatureSlogans: ['La liberté vous conduit.', 'Le confort vous accompagne.'],
  },
  es: {
    ...BASE_EN,
    subject: 'Finalización de la reserva',
    heading: 'Finalización de la reserva',
    intro:
      'Aquí tienes un resumen de todas las tarifas y datos que tenemos actualmente para tu reserva.',
    instructions:
      'Revisa la información y confirma tu reserva, o cuéntanos si necesitas ayuda. La cancelación es gratuita hasta 48 horas antes del inicio del alquiler.',
    confirmCta: 'Confirmar mi reserva',
    questionCta: 'Tengo una pregunta',
    retainNote:
      'Por favor, conserva este correo. Si más adelante necesitas modificar o cancelar la reserva, puedes hacerlo directamente desde aquí.',
    manageIntro:
      'Usa los botones siguientes para modificar o cancelar cuando lo necesites.',
    modifyCta: 'Modificar reserva',
    cancelCta: 'Cancelar reserva',
    closing: 'Un saludo',
    sections: {
      fees: 'Resumen de tarifas',
      booking: 'Datos de la reserva',
      billing: 'Detalles de facturación',
      delivery: 'Entrega / Recogida',
    },
    labels: {
      bookingCode: 'ID de reserva',
      car: 'Vehículo',
      period: 'Periodo de alquiler',
      rentalFee: 'Tarifa de alquiler',
      insurance: 'Seguro',
      deposit: 'Depósito',
      deliveryFee: 'Tarifa de entrega',
      extrasFee: 'Coste de extras',
      extrasList: 'Extras solicitados',
      adults: 'Adultos',
      children: 'Niños',
      contactName: 'Persona de contacto',
      contactEmail: 'Email de contacto',
      contactPhone: 'Teléfono de contacto',
      invoiceName: 'Nombre de facturación',
      invoiceEmail: 'Email de facturación',
      invoicePhone: 'Teléfono de facturación',
      invoiceAddress: 'Dirección de facturación',
      deliveryLocation: 'Lugar de entrega',
      deliveryType: 'Tipo de entrega',
      deliveryAddress: 'Dirección de entrega',
      arrivalFlight: 'Vuelo de llegada',
      departureFlight: 'Vuelo de salida',
      totalLabel: 'Total',
    },
    signatureRole: 'Asesor de operaciones de alquiler',
    signatureLocation: 'Fuerteventura y Lanzarote',
    signatureWebsite: 'https://zodiacsrentacar.com/es',
    signatureSlogans: ['La libertad te conduce.', 'La comodidad te acompaña.'],
  },
  it: {
    ...BASE_EN,
    subject: 'Finalizzazione della prenotazione',
    heading: 'Finalizzazione della prenotazione',
    intro:
      'Qui trovi il riepilogo di tutte le tariffe e i dati disponibili per la tua prenotazione.',
    instructions:
      'Controlla le informazioni e conferma la prenotazione oppure facci sapere se hai dubbi. La cancellazione è gratuita fino a 48 ore prima dell’inizio del noleggio.',
    confirmCta: 'Confermo la prenotazione',
    questionCta: 'Ho una domanda',
    retainNote:
      'Ti invitiamo a conservare questa email. Se in futuro desideri modificare o cancellare la prenotazione, puoi farlo direttamente da qui.',
    manageIntro:
      'Usa i pulsanti qui sotto per modificare o cancellare la prenotazione in qualsiasi momento.',
    modifyCta: 'Modifica prenotazione',
    cancelCta: 'Annulla prenotazione',
    closing: 'Cordiali saluti',
    sections: {
      fees: 'Riepilogo costi',
      booking: 'Dati della prenotazione',
      billing: 'Dettagli di fatturazione',
      delivery: 'Consegna / Ritiro',
    },
    labels: {
      bookingCode: 'ID prenotazione',
      car: 'Auto',
      period: 'Periodo di noleggio',
      rentalFee: 'Tariffa di noleggio',
      insurance: 'Assicurazione',
      deposit: 'Deposito',
      deliveryFee: 'Costo consegna',
      extrasFee: 'Costo extra',
      extrasList: 'Extra richiesti',
      adults: 'Adulti',
      children: 'Bambini',
      contactName: 'Contatto',
      contactEmail: 'Email contatto',
      contactPhone: 'Telefono contatto',
      invoiceName: 'Nome fatturazione',
      invoiceEmail: 'Email fatturazione',
      invoicePhone: 'Telefono fatturazione',
      invoiceAddress: 'Indirizzo fatturazione',
      deliveryLocation: 'Località consegna',
      deliveryType: 'Tipo consegna',
      deliveryAddress: 'Indirizzo consegna',
      arrivalFlight: 'Volo di arrivo',
      departureFlight: 'Volo di partenza',
      totalLabel: 'Totale',
    },
    signatureRole: 'Consulente operazioni di noleggio',
    signatureLocation: 'Fuerteventura e Lanzarote',
    signatureWebsite: 'https://zodiacsrentacar.com/it',
    signatureSlogans: ['La libertà ti guida.', 'Il comfort ti accompagna.'],
  },
  sk: {
    ...BASE_EN,
    subject: 'Dokončenie rezervácie',
    heading: 'Dokončenie rezervácie',
    intro:
      'Prinášame prehľad všetkých poplatkov a údajov, ktoré aktuálne k rezervácii máme.',
    instructions:
      'Skontroluj prosím údaje a potvrď rezerváciu alebo nám daj vedieť, či je niečo nejasné. Zrušenie je bez poplatku najneskôr 48 hodín pred začiatkom prenájmu.',
    confirmCta: 'Potvrdiť rezerváciu',
    questionCta: 'Mám otázku',
    retainNote:
      'Prosíme, nevymazávaj tento e-mail. Ak budeš chcieť rezerváciu neskôr upraviť alebo zrušiť, môžeš to urobiť priamo odtiaľto.',
    manageIntro:
      'Na úpravu alebo zrušenie použij tlačidlá nižšie kedykoľvek potrebuješ.',
    modifyCta: 'Upraviť rezerváciu',
    cancelCta: 'Zrušiť rezerváciu',
    closing: 'S pozdravom',
    sections: {
      fees: 'Prehľad poplatkov',
      booking: 'Údaje o rezervácii',
      billing: 'Fakturačné údaje',
      delivery: 'Doručenie / Prevzatie',
    },
    labels: {
      bookingCode: 'Číslo rezervácie',
      car: 'Vozidlo',
      period: 'Obdobie prenájmu',
      rentalFee: 'Prenájomné',
      insurance: 'Poistenie',
      deposit: 'Kaucia',
      deliveryFee: 'Poplatok za doručenie',
      extrasFee: 'Poplatok za extra služby',
      extrasList: 'Vyžiadané extra služby',
      adults: 'Dospelí',
      children: 'Deti',
      contactName: 'Kontakt',
      contactEmail: 'E-mail kontaktu',
      contactPhone: 'Telefón kontaktu',
      invoiceName: 'Fakturačné meno',
      invoiceEmail: 'Fakturačný e-mail',
      invoicePhone: 'Fakturačný telefón',
      invoiceAddress: 'Fakturačná adresa',
      deliveryLocation: 'Miesto doručenia',
      deliveryType: 'Typ doručenia',
      deliveryAddress: 'Adresa doručenia',
      arrivalFlight: 'Prílet',
      departureFlight: 'Odlet',
      totalLabel: 'Spolu',
    },
    signatureRole: 'Poradca pre prenájom vozidiel',
    signatureLocation: 'Fuerteventura a Lanzarote',
    signatureWebsite: 'https://zodiacsrentacar.com/sk',
    signatureSlogans: ['Sloboda vedie.', 'Komfort sprevádza.'],
  },
  cz: {
    ...BASE_EN,
    subject: 'Dokončení rezervace',
    heading: 'Dokončení rezervace',
    intro:
      'Níže najdete souhrn všech poplatků a údajů, které k rezervaci máme.',
    instructions:
      'Zkontrolujte prosím informace a potvrďte rezervaci, nebo nám napište, pokud máte dotazy. Zrušení je zdarma nejpozději 48 hodin před začátkem pronájmu.',
    confirmCta: 'Potvrdit rezervaci',
    questionCta: 'Mám dotaz',
    retainNote:
      'Prosíme, nemažte tento e-mail. Pokud budete chtít rezervaci později upravit nebo zrušit, můžete to udělat přímo odsud.',
    manageIntro:
      'K úpravě nebo zrušení použijte kdykoli tlačítka níže.',
    modifyCta: 'Upravit rezervaci',
    cancelCta: 'Zrušit rezervaci',
    closing: 'S pozdravem',
    sections: {
      fees: 'Přehled poplatků',
      booking: 'Údaje o rezervaci',
      billing: 'Fakturační údaje',
      delivery: 'Doručení / Převzetí',
    },
    labels: {
      bookingCode: 'Číslo rezervace',
      car: 'Vozidlo',
      period: 'Doba pronájmu',
      rentalFee: 'Nájemné',
      insurance: 'Pojištění',
      deposit: 'Kauce',
      deliveryFee: 'Poplatek za doručení',
      extrasFee: 'Poplatek za doplňky',
      extrasList: 'Vyžádané doplňky',
      adults: 'Dospělí',
      children: 'Děti',
      contactName: 'Kontakt',
      contactEmail: 'E-mail kontaktu',
      contactPhone: 'Telefon kontaktu',
      invoiceName: 'Fakturační jméno',
      invoiceEmail: 'Fakturační e-mail',
      invoicePhone: 'Fakturační telefon',
      invoiceAddress: 'Fakturační adresa',
      deliveryLocation: 'Místo doručení',
      deliveryType: 'Typ doručení',
      deliveryAddress: 'Adresa doručení',
      arrivalFlight: 'Přílet',
      departureFlight: 'Odlet',
      totalLabel: 'Celkem',
    },
    signatureRole: 'Poradce pro provoz půjčoven',
    signatureLocation: 'Fuerteventura a Lanzarote',
    signatureWebsite: 'https://zodiacsrentacar.com/cz',
    signatureSlogans: ['Svoboda vede.', 'Komfort provází.'],
  },
  se: {
    ...BASE_EN,
    subject: 'Slutför bokningen',
    heading: 'Slutför bokningen',
    intro:
      'Här är en översikt över alla kostnader och uppgifter som vi har för din bokning.',
    instructions:
      'Granska informationen och bekräfta bokningen, eller meddela oss om du har frågor. Avbokning är kostnadsfri fram till 48 timmar före hyrans start.',
    confirmCta: 'Bekräfta bokningen',
    questionCta: 'Jag har en fråga',
    retainNote:
      'Spara gärna det här mejlet. Om du senare behöver ändra eller avboka kan du göra det direkt härifrån.',
    manageIntro:
      'Använd knapparna nedan för att ändra eller avboka när som helst.',
    modifyCta: 'Ändra bokning',
    cancelCta: 'Avboka bokning',
    closing: 'Vänliga hälsningar',
    sections: {
      fees: 'Kostnadssammanställning',
      booking: 'Bokningsuppgifter',
      billing: 'Faktureringsuppgifter',
      delivery: 'Leverans / Hämtning',
    },
    labels: {
      bookingCode: 'Boknings-ID',
      car: 'Bil',
      period: 'Hyresperiod',
      rentalFee: 'Hyresavgift',
      insurance: 'Försäkring',
      deposit: 'Deposition',
      deliveryFee: 'Leveranskostnad',
      extrasFee: 'Kostnad för tillval',
      extrasList: 'Önskade tillval',
      adults: 'Vuxna',
      children: 'Barn',
      contactName: 'Kontaktperson',
      contactEmail: 'Kontakt e-post',
      contactPhone: 'Kontakt telefon',
      invoiceName: 'Fakturanamn',
      invoiceEmail: 'Faktura-e-post',
      invoicePhone: 'Fakturatelefon',
      invoiceAddress: 'Fakturaadress',
      deliveryLocation: 'Leveransplats',
      deliveryType: 'Leveranssätt',
      deliveryAddress: 'Leveransadress',
      arrivalFlight: 'Ankommande flyg',
      departureFlight: 'Avgående flyg',
      totalLabel: 'Totalt',
    },
    signatureRole: 'Rådgivare för uthyrningsverksamhet',
    signatureLocation: 'Fuerteventura & Lanzarote',
    signatureWebsite: 'https://zodiacsrentacar.com/se',
    signatureSlogans: ['Friheten leder.', 'Komforten följer med.'],
  },
  no: {
    ...BASE_EN,
    subject: 'Fullfør bestillingen',
    heading: 'Fullfør bestillingen',
    intro:
      'Her finner du en oversikt over alle kostnader og detaljer vi har for bestillingen.',
    instructions:
      'Se gjennom informasjonen, og bekreft bestillingen eller gi oss beskjed hvis du har spørsmål. Kostnadsfri avbestilling er mulig inntil 48 timer før leiestart.',
    confirmCta: 'Bekreft bestillingen',
    questionCta: 'Jeg har et spørsmål',
    retainNote:
      'Vennligst behold denne e-posten. Hvis du senere vil endre eller avbestille, kan du gjøre det direkte herfra.',
    manageIntro:
      'Bruk knappene under for å endre eller avbestille når det passer deg.',
    modifyCta: 'Endre bestilling',
    cancelCta: 'Avbestill bestilling',
    closing: 'Med vennlig hilsen',
    sections: {
      fees: 'Kostnadsoversikt',
      booking: 'Bestillingsdata',
      billing: 'Fakturadetaljer',
      delivery: 'Levering / Henting',
    },
    labels: {
      bookingCode: 'Bestillings-ID',
      car: 'Bil',
      period: 'Leieperiode',
      rentalFee: 'Leiepris',
      insurance: 'Forsikring',
      deposit: 'Depositum',
      deliveryFee: 'Leveringsgebyr',
      extrasFee: 'Pris for ekstrautstyr',
      extrasList: 'Ønskede tillegg',
      adults: 'Voksne',
      children: 'Barn',
      contactName: 'Kontaktperson',
      contactEmail: 'Kontakt e-post',
      contactPhone: 'Kontakt telefon',
      invoiceName: 'Fakturanavn',
      invoiceEmail: 'Faktura e-post',
      invoicePhone: 'Faktura telefon',
      invoiceAddress: 'Fakturaadresse',
      deliveryLocation: 'Leveringssted',
      deliveryType: 'Leveringstype',
      deliveryAddress: 'Leveringsadresse',
      arrivalFlight: 'Ankommende flight',
      departureFlight: 'Avreiseflight',
      totalLabel: 'Totalt',
    },
    signatureRole: 'Rådgiver for leieoperasjoner',
    signatureLocation: 'Fuerteventura & Lanzarote',
    signatureWebsite: 'https://zodiacsrentacar.com/no',
    signatureSlogans: ['Frihet leder.', 'Komfort følger med.'],
  },
  dk: {
    ...BASE_EN,
    subject: 'Færdiggør din booking',
    heading: 'Færdiggør din booking',
    intro:
      'Her er et overblik over alle gebyrer og oplysninger, vi har på din booking.',
    instructions:
      'Gennemgå oplysningerne og bekræft bookingen – eller kontakt os, hvis du har spørgsmål. Afbestilling er gratis indtil 48 timer før lejemålets start.',
    confirmCta: 'Bekræft booking',
    questionCta: 'Jeg har et spørgsmål',
    retainNote:
      'Gem venligst denne e-mail. Hvis du senere vil ændre eller annullere, kan du gøre det direkte herfra.',
    manageIntro:
      'Brug knapperne herunder til at ændre eller annullere, når du har behov.',
    modifyCta: 'Redigér booking',
    cancelCta: 'Annuller booking',
    closing: 'Med venlig hilsen',
    sections: {
      fees: 'Prisoversigt',
      booking: 'Bookingdata',
      billing: 'Faktureringsoplysninger',
      delivery: 'Levering / Afhentning',
    },
    labels: {
      bookingCode: 'Booking-ID',
      car: 'Bil',
      period: 'Lejeperiode',
      rentalFee: 'Lejepris',
      insurance: 'Forsikring',
      deposit: 'Depositum',
      deliveryFee: 'Leveringsgebyr',
      extrasFee: 'Pris for ekstraudstyr',
      extrasList: 'Ønskede ekstra',
      adults: 'Voksne',
      children: 'Børn',
      contactName: 'Kontaktperson',
      contactEmail: 'Kontakt e-mail',
      contactPhone: 'Kontakt telefon',
      invoiceName: 'Fakturanavn',
      invoiceEmail: 'Faktura e-mail',
      invoicePhone: 'Faktura telefon',
      invoiceAddress: 'Fakturaadresse',
      deliveryLocation: 'Leveringssted',
      deliveryType: 'Leveringstype',
      deliveryAddress: 'Leveringsadresse',
      arrivalFlight: 'Ankommende fly',
      departureFlight: 'Afrejsende fly',
      totalLabel: 'I alt',
    },
    signatureRole: 'Rådgiver for udlejningsdrift',
    signatureLocation: 'Fuerteventura & Lanzarote',
    signatureWebsite: 'https://zodiacsrentacar.com/dk',
    signatureSlogans: ['Frihed leder.', 'Komfort følger med.'],
  },
  pl: {
    ...BASE_EN,
    subject: 'Finalizacja rezerwacji',
    heading: 'Finalizacja rezerwacji',
    intro:
      'Poniżej znajdziesz zestawienie wszystkich opłat i danych związanych z Twoją rezerwacją.',
    instructions:
      'Sprawdź informacje i potwierdź rezerwację lub daj nam znać, jeśli masz pytania. Anulacja jest bezpłatna najpóźniej 48 godzin przed rozpoczęciem wynajmu.',
    confirmCta: 'Potwierdzam rezerwację',
    questionCta: 'Mam pytanie',
    retainNote:
      'Prosimy, nie usuwaj tej wiadomości. Jeśli później będziesz chciał zmienić lub anulować rezerwację, zrobisz to bezpośrednio stąd.',
    manageIntro:
      'Użyj przycisków poniżej, aby w razie potrzeby zmienić lub anulować.',
    modifyCta: 'Zmień rezerwację',
    cancelCta: 'Anuluj rezerwację',
    closing: 'Pozdrawiamy',
    sections: {
      fees: 'Podsumowanie opłat',
      booking: 'Dane rezerwacji',
      billing: 'Dane do faktury',
      delivery: 'Dostawa / Odbiór',
    },
    labels: {
      bookingCode: 'Numer rezerwacji',
      car: 'Samochód',
      period: 'Okres wynajmu',
      rentalFee: 'Opłata za wynajem',
      insurance: 'Ubezpieczenie',
      deposit: 'Kaucja',
      deliveryFee: 'Opłata za dostawę',
      extrasFee: 'Opłata za dodatki',
      extrasList: 'Zamówione dodatki',
      adults: 'Dorośli',
      children: 'Dzieci',
      contactName: 'Osoba kontaktowa',
      contactEmail: 'Email kontaktowy',
      contactPhone: 'Telefon kontaktowy',
      invoiceName: 'Nazwa do faktury',
      invoiceEmail: 'Email do faktury',
      invoicePhone: 'Telefon do faktury',
      invoiceAddress: 'Adres do faktury',
      deliveryLocation: 'Miejsce dostawy',
      deliveryType: 'Typ dostawy',
      deliveryAddress: 'Adres dostawy',
      arrivalFlight: 'Lot przylotowy',
      departureFlight: 'Lot odlotowy',
      totalLabel: 'Suma',
    },
    signatureRole: 'Doradca ds. operacji wynajmu',
    signatureLocation: 'Fuerteventura i Lanzarote',
    signatureWebsite: 'https://zodiacsrentacar.com/pl',
    signatureSlogans: ['Wolność prowadzi.', 'Komfort towarzyszy.'],
  },
};

export const getFinalizationCopy = (locale?: string | null) => {
  if (!locale) return FINALIZATION_COPY.en;
  const key = locale.toLowerCase();
  return FINALIZATION_COPY[key] ?? FINALIZATION_COPY.en;
};
